### ISSUE TITLE
Scenario_runner: Windows install, path problems? 

### ISSUE THREAD

**Issue by Lu7913** [carla-simulator/scenario_runner#596]
Hello,
I'm new to the Carla and scenario runner and I have the following problem when trying to start an example scenario. 

Running: py scenario_runner.py 

resulted in error: 
from agents.navigation.basic_agent import BasicAgent, LocalPlanner
ModuleNotFoundError: No module named 'agents.navigation'

Something seems to wrong with the PYTHONPATH. I followed [https://github.com/carla-simulator/scenario_runner/blob/master/Docs/getting_scenariorunner.md](url) instructions and set path accordingly. I have also tried all kinds of variations of this path, but it doesn't works.
All agents.xx modules cannot be found.
Thank you. 

 - OS: Windows 10
 - CARLA Version 9.9
 - Python version 3.7
 - ScenarioRunner 9.9

**Comment by Lu7913** [comment]
I had to install additional python modules.

**Comment by Lu7913** [comment]
Could this be related to tensorflow problems which I had, (had to downgrade to 1.15.3)?

**Comment by glopezdiest** [comment]
Hey @Lu7913. That's definitely related to the PYTHONPATH. Could you please post it here? Theoretically, it should always work as long as you have this line:

> %CARLA_ROOT%\PythonAPI\carla

**Comment by Lu7913** [comment]
Hi, I set the path accordingly to manuals which is 

> PYTHONPATH=%PYTHONPATH%:%CARLA_ROOT%\PythonAPI (C:\Users\%user%\AppData\Local\Programs\Python\Python37:D:\%user%\carla\PythonAPI\carla)

with %PYTHONPATH% before %CARLA_ROOT%, removing %PYTHONPATH%, helped.

Now when running `python scenario_runner.py --scenario FollowLeadingVehicle_1 --reloadWorld` and then `python manula.control.py` I got:
>No module named 'examples.manual_control'

Are there more Paths to be set different than in manual?
 
To add why I had to downgrade tensorflow, because tensorflow.contrib is apparently not supported in the tensorflow>2.xx. So running with tensorflow 1.15 resulted in:
`The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.`
despite I did the necessary updates, problem remained until now when I have fixed the path. 
Should ScenarioRunner work with tensorflow greater than 2.00? Because downgrading it created a lot of mess with different  modules compatibility. Or it was just effect of false PYTHONPATH?

Thank you for your help.

**Comment by glopezdiest** [comment]
Well, you solved one problem, but you definitely need more variables to be added. You seem to also be missing the PythonAPI:

`set PYTHONPATH=%PYTHONPATH%:%CARLA_ROOT%\PythonAPI`

From the Docs, you need to add all of this to the PYTHONPATH for ScenarioRunner to work. Please make sure you have them all

![image](https://user-images.githubusercontent.com/58212725/88261502-bcb83080-ccc6-11ea-912e-672c50279775.png)

**Comment by Lu7913** [comment]
Yes of course, I had all this paths added as described in docs, days ago.  The thing just don't work for me. Could this be related to having Carla installed on different disk that python? 
I tried for all other paths the same thing, that helped me minutes for one, but it seems that it is not working.

**Comment by glopezdiest** [comment]
By using the set command, you are only adding them to the current terminal, but whenever you close it, the PYTHONPATH is gone.

You have to permanently set them, by going to *edit the environment variables of this account*. This can be quickly accessed by writing *env* on the Windows' search panel.

From the PYTHONPATH you posted, you seem to lack many of the lines

**Comment by Lu7913** [comment]
Yes I did all that. 
![PYTHONPATH1](https://user-images.githubusercontent.com/68107933/88265140-3eab5800-cccd-11ea-8c96-91072c31235f.PNG)

**Comment by glopezdiest** [comment]
I see, I misunderstood you then. I actually don't know why it is failling then.

If you can run the FollowLeadingVehicle scenario without problems, then the *.egg* file being found, and also the *PythonAPI\carla* folder, but for some reason you can't find the PythonAPI

**Comment by Lu7913** [comment]
Hi,
I managed to avoid problems with path, by not building Carla but, downloading and extracting it.
When trying to run example scenario with ScenarioRunner i got the following error:
`AttributeError: module 'signal' has no attribute 'SIGHUP'`
Apparently this should not be run on windows. I commented out line 128 in scenario_runner.py and for now, seems to work. how to avoid this problem on windows otherwise?

There remain a problem with opening Unreal Engine project, when trying to open it and rebuilding it crashes and i got an error:
`CarlaUE4 could not be compiled. Try rebuilding from source manually`, because project was made in different version, but I use UE 4.24.3.

But if I understand correctly, now i can't rebuild it from source, because I downloaded it and extracted? Correct me if I am wrong.
How 
As it seems when I build Carla from source, it is not building correctly, what could be the issue?
I tried building from source many times, with different pythons versions, assets, but only the latest Carla.

**Comment by glopezdiest** [comment]
> AttributeError: module 'signal' has no attribute 'SIGHUP'

Yeah, we fixed that [here](https://github.com/carla-simulator/scenario_runner/pull/561) but i don't think it is in any release yet. As far as I know,  the signal just doesn't exist for Windows.

Regarding your building problems, I actually don't know, I had no issues installing CARLA. If I understand correctly, you can *make clean* , remove the carla folder and it should remove everything, but I'm not sure.

**Comment by Lu7913** [comment]
I did that when building from source, now I can't build UE project manually because I just downloaded and extracted Carla, right?

I'm planing to switch to Linux, but for now I'm stuck with Windows.

Again, thank you.

**Comment by Lu7913** [comment]
Hi,
after some time me again. Yeah so... prebuild Carla works on Windows, I have built Carla from source on Kubuntu, which was working great with ScenarioRunner until I tried to install ROS and changed default python. I switched back default python and there is same problem that I have on Windows. Clearly I'm doing something wrong, but don't know what.

If this maybe is pointing to where the problem might be? I will also mention that when building on Windows .egg for default python is created only, on Kubuntu .egg files were created for python2 and python3.

I'm doing quite a lot of research, but no luck. To me this seems to be some silly mistake which I'm repeating.

**Comment by Lu7913** [comment]
I have managed to solve the issue on Kubuntu, with manually deleting Carla module and then reinstalling it.
With Windows there seems to be only one specific way of setting up PYTHONPATH, which works for me:

%PYTHONPATH%;%CARLA_ROOT%\PythonAPI\carla\dist\carla-<VERSION>.egg
%CARLA_ROOT%\PythonAPI\carla\agents
%CARLA_ROOT%\PythonAPI\carla
%CARLA_ROOT%\PythonAPI

I have talked to some people about this, but they are also not sure why this works and nothing else.

**Comment by aczy118** [comment]
Hi,
Can you please explain how did you solve the problem for Windows? I have tried your last entry but I am still getting 'no module named carla' . Why is it not working? 
Thanks.

**Comment by Lu7913** [comment]
First make sure that Carla server is running fine and you can connect python client to it. Than make sure that you replace text between %% with your corresponding location.  
![image](https://user-images.githubusercontent.com/68107933/94430428-302d6100-0194-11eb-8330-88c2d9c4c11e.png)

Try with prebuild version of Carla first. I haven't had issues with that.

**Comment by sterres** [comment]
Your problem might be the spelling error in the last line of the command list - the use ":" as separator instead of ";".
It is fixed in the documenation but the screenshot here is still outdated.

**Comment by sterres** [comment]
> Hi, I set the path accordingly to manuals which is
> 
> > PYTHONPATH=%PYTHONPATH%:%CARLA_ROOT%\PythonAPI (C:\Users%user%\AppData\Local\Programs\Python\Python37:D:%user%\carla\PythonAPI\carla)
> 
> with %PYTHONPATH% before %CARLA_ROOT%, removing %PYTHONPATH%, helped.
> 
> Now when running `python scenario_runner.py --scenario FollowLeadingVehicle_1 --reloadWorld` and then `python manula.control.py` I got:
> 
> > No module named 'examples.manual_control'
> 
> Also no actors are spawned.
> 
> Are there more Paths to be set different than in manual?
> 
> To add why I had to downgrade tensorflow, because tensorflow.contrib is apparently not supported in the tensorflow>2.xx. So running with tensorflow 1.15 resulted in:
> `The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions`instead of`tf.distributions`.`
> despite I did the necessary updates, problem remained until now when I have fixed the path.
> Should ScenarioRunner work with tensorflow greater than 2.00? Because downgrading it created a lot of mess with different modules compatibility. Or it was just effect of false PYTHONPATH?
> 
> Thank you for your help.


Just came accross the same isseue .... my solution: 

Go to your Carla examples folder (subfolder PythonAPI\examples) and create a file with name **"__init__.py"**. This will allow the script to load the Carla Python modules without error
